logger:
  format: json
  appName: honey_node
  level: info
system:
  grpcManageAddr: "111.111.111.133:8081"          # rpc的运行地址
  network: "ens33"
  uid: "c6807dbc-e881-46d7-8408-d949333b02bb"
  evePath: "deploy/suricata/logs/eve.json"
#  webAddr: "127.0.0.1:8089"                    # web的运行地址
filterNetworkList:
  - br-
  - docker
  - mc_
mq:
  user: admin
  password: password
  host: 111.111.111.133
  port: 5671
  createIpExchangeName: createIpExchange
  deleteIpExchangeName: deleteIpExchange
  bindPortExchangeName: bindPortExchange
  ssl: true
  clientCertificate: mq_cert/client_certificate.pem #客户端证书
  clientKey: mq_cert/client_key.pem           #客户端私钥
  caCertificate: mq_cert/ca_certificate.pem        #ca证书
  alertTopic: alert_topic
db:
  db_name: "gorm.db"
  maxIdleConns: 2
  maxOpenConns: 100
  connMaxLifeTime: 10000