logger:
  format: json
  appName: honey_node
  level: info
system:
  grpcManageAddr: ":8081"          # rpc的运行地址
  network: "ens33"
  uid: "c6807dbc-e881-46d7-8408-d949333b02bb"
#  webAddr: "127.0.0.1:8089"                    # web的运行地址
filterNetworkList:
  - br-
  - docker
  - mc_
mq:
  user: admin
  password: password
  host: 192.168.177.129
  port: 5672
  createIpExchangeName: createIpExchange
  deleteIpExchangeName: deleteIpExchange
  bindPortExchangeName: bindPortExchange
  ssl: false
  clientCertificate:    #客户端证书
  clientKey:            #客户端私钥
  caCertificate:        #ca证书