// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: internal/rpc/node.proto

package node_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdType int32

const (
	CmdType_cmdNetworkFlushType CmdType = 0
	CmdType_cmdNetScanType      CmdType = 1
	CmdType_cmdNodeRemoveType   CmdType = 2
	CmdType_cmdPingType         CmdType = 3
)

// Enum value maps for CmdType.
var (
	CmdType_name = map[int32]string{
		0: "cmdNetworkFlushType",
		1: "cmdNetScanType",
		2: "cmdNodeRemoveType",
		3: "cmdPingType",
	}
	CmdType_value = map[string]int32{
		"cmdNetworkFlushType": 0,
		"cmdNetScanType":      1,
		"cmdNodeRemoveType":   2,
		"cmdPingType":         3,
	}
)

func (x CmdType) Enum() *CmdType {
	p := new(CmdType)
	*p = x
	return p
}

func (x CmdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_rpc_node_proto_enumTypes[0].Descriptor()
}

func (CmdType) Type() protoreflect.EnumType {
	return &file_internal_rpc_node_proto_enumTypes[0]
}

func (x CmdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdType.Descriptor instead.
func (CmdType) EnumDescriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{0}
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_internal_rpc_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// HelloRequest 请求内容
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	NodeUid       string                 `protobuf:"bytes,3,opt,name=node_uid,json=nodeUid,proto3" json:"node_uid,omitempty"` // 消息号
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,5,opt,name=commit,proto3" json:"commit,omitempty"`
	SystemInfo    *SystemInfoMessage     `protobuf:"bytes,6,opt,name=systemInfo,proto3" json:"systemInfo,omitempty"`
	ResourceInfo  *ResourceMessage       `protobuf:"bytes,7,opt,name=resourceInfo,proto3" json:"resourceInfo,omitempty"`
	NetworkList   []*NetworkInfoMessage  `protobuf:"bytes,8,rep,name=networkList,proto3" json:"networkList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_rpc_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *RegisterRequest) GetNodeUid() string {
	if x != nil {
		return x.NodeUid
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *RegisterRequest) GetSystemInfo() *SystemInfoMessage {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

func (x *RegisterRequest) GetResourceInfo() *ResourceMessage {
	if x != nil {
		return x.ResourceInfo
	}
	return nil
}

func (x *RegisterRequest) GetNetworkList() []*NetworkInfoMessage {
	if x != nil {
		return x.NetworkList
	}
	return nil
}

type NodeResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeUid       string                 `protobuf:"bytes,1,opt,name=node_uid,json=nodeUid,proto3" json:"node_uid,omitempty"` // 消息号
	ResourceInfo  *ResourceMessage       `protobuf:"bytes,2,opt,name=resourceInfo,proto3" json:"resourceInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResourceRequest) Reset() {
	*x = NodeResourceRequest{}
	mi := &file_internal_rpc_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResourceRequest) ProtoMessage() {}

func (x *NodeResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResourceRequest.ProtoReflect.Descriptor instead.
func (*NodeResourceRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{2}
}

func (x *NodeResourceRequest) GetNodeUid() string {
	if x != nil {
		return x.NodeUid
	}
	return ""
}

func (x *NodeResourceRequest) GetResourceInfo() *ResourceMessage {
	if x != nil {
		return x.ResourceInfo
	}
	return nil
}

type SystemInfoMessage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HostName            string                 `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	DistributionVersion string                 `protobuf:"bytes,2,opt,name=distributionVersion,proto3" json:"distributionVersion,omitempty"`
	CoreVersion         string                 `protobuf:"bytes,3,opt,name=coreVersion,proto3" json:"coreVersion,omitempty"`
	SystemType          string                 `protobuf:"bytes,4,opt,name=systemType,proto3" json:"systemType,omitempty"`
	StartTime           string                 `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SystemInfoMessage) Reset() {
	*x = SystemInfoMessage{}
	mi := &file_internal_rpc_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoMessage) ProtoMessage() {}

func (x *SystemInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoMessage.ProtoReflect.Descriptor instead.
func (*SystemInfoMessage) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{3}
}

func (x *SystemInfoMessage) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *SystemInfoMessage) GetDistributionVersion() string {
	if x != nil {
		return x.DistributionVersion
	}
	return ""
}

func (x *SystemInfoMessage) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *SystemInfoMessage) GetSystemType() string {
	if x != nil {
		return x.SystemType
	}
	return ""
}

func (x *SystemInfoMessage) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

type ResourceMessage struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CpuCount              int64                  `protobuf:"varint,1,opt,name=cpuCount,proto3" json:"cpuCount,omitempty"`
	CpuUseRate            float32                `protobuf:"fixed32,2,opt,name=cpuUseRate,proto3" json:"cpuUseRate,omitempty"`
	MemTotal              int64                  `protobuf:"varint,3,opt,name=memTotal,proto3" json:"memTotal,omitempty"`
	MemUseRate            float32                `protobuf:"fixed32,4,opt,name=memUseRate,proto3" json:"memUseRate,omitempty"`
	DiskTotal             int64                  `protobuf:"varint,5,opt,name=diskTotal,proto3" json:"diskTotal,omitempty"`
	DiskUseRate           float32                `protobuf:"fixed32,6,opt,name=diskUseRate,proto3" json:"diskUseRate,omitempty"`
	NodePath              string                 `protobuf:"bytes,7,opt,name=nodePath,proto3" json:"nodePath,omitempty"`
	NodeResourceOccupancy int64                  `protobuf:"varint,8,opt,name=nodeResourceOccupancy,proto3" json:"nodeResourceOccupancy,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ResourceMessage) Reset() {
	*x = ResourceMessage{}
	mi := &file_internal_rpc_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMessage) ProtoMessage() {}

func (x *ResourceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMessage.ProtoReflect.Descriptor instead.
func (*ResourceMessage) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceMessage) GetCpuCount() int64 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *ResourceMessage) GetCpuUseRate() float32 {
	if x != nil {
		return x.CpuUseRate
	}
	return 0
}

func (x *ResourceMessage) GetMemTotal() int64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *ResourceMessage) GetMemUseRate() float32 {
	if x != nil {
		return x.MemUseRate
	}
	return 0
}

func (x *ResourceMessage) GetDiskTotal() int64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *ResourceMessage) GetDiskUseRate() float32 {
	if x != nil {
		return x.DiskUseRate
	}
	return 0
}

func (x *ResourceMessage) GetNodePath() string {
	if x != nil {
		return x.NodePath
	}
	return ""
}

func (x *ResourceMessage) GetNodeResourceOccupancy() int64 {
	if x != nil {
		return x.NodeResourceOccupancy
	}
	return 0
}

type NetworkInfoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Net           string                 `protobuf:"bytes,3,opt,name=net,proto3" json:"net,omitempty"`
	Mask          int32                  `protobuf:"varint,4,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInfoMessage) Reset() {
	*x = NetworkInfoMessage{}
	mi := &file_internal_rpc_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfoMessage) ProtoMessage() {}

func (x *NetworkInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfoMessage.ProtoReflect.Descriptor instead.
func (*NetworkInfoMessage) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkInfoMessage) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *NetworkInfoMessage) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NetworkInfoMessage) GetNet() string {
	if x != nil {
		return x.Net
	}
	return ""
}

func (x *NetworkInfoMessage) GetMask() int32 {
	if x != nil {
		return x.Mask
	}
	return 0
}

type CmdRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CmdType               CmdType                `protobuf:"varint,1,opt,name=cmdType,proto3,enum=node_rpc.CmdType" json:"cmdType,omitempty"`
	TaskID                string                 `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	NetworkFlushInMessage *NetworkFlushInMessage `protobuf:"bytes,3,opt,name=NetworkFlushInMessage,proto3" json:"NetworkFlushInMessage,omitempty"`
	NetScanInMessage      *NetScanInMessage      `protobuf:"bytes,4,opt,name=NetScanInMessage,proto3" json:"NetScanInMessage,omitempty"`
	NodeRemoveInMessage   *NodeRemoveInMessage   `protobuf:"bytes,5,opt,name=NodeRemoveInMessage,proto3" json:"NodeRemoveInMessage,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CmdRequest) Reset() {
	*x = CmdRequest{}
	mi := &file_internal_rpc_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdRequest) ProtoMessage() {}

func (x *CmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdRequest.ProtoReflect.Descriptor instead.
func (*CmdRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{6}
}

func (x *CmdRequest) GetCmdType() CmdType {
	if x != nil {
		return x.CmdType
	}
	return CmdType_cmdNetworkFlushType
}

func (x *CmdRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *CmdRequest) GetNetworkFlushInMessage() *NetworkFlushInMessage {
	if x != nil {
		return x.NetworkFlushInMessage
	}
	return nil
}

func (x *CmdRequest) GetNetScanInMessage() *NetScanInMessage {
	if x != nil {
		return x.NetScanInMessage
	}
	return nil
}

func (x *CmdRequest) GetNodeRemoveInMessage() *NodeRemoveInMessage {
	if x != nil {
		return x.NodeRemoveInMessage
	}
	return nil
}

type CmdResponse struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	CmdType                CmdType                 `protobuf:"varint,1,opt,name=cmdType,proto3,enum=node_rpc.CmdType" json:"cmdType,omitempty"`
	TaskID                 string                  `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	NodeID                 string                  `protobuf:"bytes,3,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Code                   int32                   `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	ErrorMsg               string                  `protobuf:"bytes,5,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	NetworkFlushOutMessage *NetworkFlushOutMessage `protobuf:"bytes,6,opt,name=NetworkFlushOutMessage,proto3" json:"NetworkFlushOutMessage,omitempty"`
	NetScanOutMessage      *NetScanOutMessage      `protobuf:"bytes,7,opt,name=NetScanOutMessage,proto3" json:"NetScanOutMessage,omitempty"`
	NodeRemoveOutMessage   *NodeRemoveOutMessage   `protobuf:"bytes,8,opt,name=NodeRemoveOutMessage,proto3" json:"NodeRemoveOutMessage,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CmdResponse) Reset() {
	*x = CmdResponse{}
	mi := &file_internal_rpc_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdResponse) ProtoMessage() {}

func (x *CmdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdResponse.ProtoReflect.Descriptor instead.
func (*CmdResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{7}
}

func (x *CmdResponse) GetCmdType() CmdType {
	if x != nil {
		return x.CmdType
	}
	return CmdType_cmdNetworkFlushType
}

func (x *CmdResponse) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *CmdResponse) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *CmdResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CmdResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *CmdResponse) GetNetworkFlushOutMessage() *NetworkFlushOutMessage {
	if x != nil {
		return x.NetworkFlushOutMessage
	}
	return nil
}

func (x *CmdResponse) GetNetScanOutMessage() *NetScanOutMessage {
	if x != nil {
		return x.NetScanOutMessage
	}
	return nil
}

func (x *CmdResponse) GetNodeRemoveOutMessage() *NodeRemoveOutMessage {
	if x != nil {
		return x.NodeRemoveOutMessage
	}
	return nil
}

type NetworkFlushInMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FilterNetworkName []string               `protobuf:"bytes,1,rep,name=filterNetworkName,proto3" json:"filterNetworkName,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetworkFlushInMessage) Reset() {
	*x = NetworkFlushInMessage{}
	mi := &file_internal_rpc_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkFlushInMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkFlushInMessage) ProtoMessage() {}

func (x *NetworkFlushInMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkFlushInMessage.ProtoReflect.Descriptor instead.
func (*NetworkFlushInMessage) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkFlushInMessage) GetFilterNetworkName() []string {
	if x != nil {
		return x.FilterNetworkName
	}
	return nil
}

type NetworkFlushOutMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkList   []*NetworkInfoMessage  `protobuf:"bytes,1,rep,name=networkList,proto3" json:"networkList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkFlushOutMessage) Reset() {
	*x = NetworkFlushOutMessage{}
	mi := &file_internal_rpc_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkFlushOutMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkFlushOutMessage) ProtoMessage() {}

func (x *NetworkFlushOutMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkFlushOutMessage.ProtoReflect.Descriptor instead.
func (*NetworkFlushOutMessage) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkFlushOutMessage) GetNetworkList() []*NetworkInfoMessage {
	if x != nil {
		return x.NetworkList
	}
	return nil
}

type NetScanInMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`           // 使用哪一个网卡进行arp探测
	IpRange       string                 `protobuf:"bytes,2,opt,name=ipRange,proto3" json:"ipRange,omitempty"`           // 需要扫描的ip列表
	FilterIPList  []string               `protobuf:"bytes,3,rep,name=filterIPList,proto3" json:"filterIPList,omitempty"` // 不需要扫描的ip列表
	NetID         uint32                 `protobuf:"varint,4,opt,name=netID,proto3" json:"netID,omitempty"`              // 网络id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetScanInMessage) Reset() {
	*x = NetScanInMessage{}
	mi := &file_internal_rpc_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetScanInMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetScanInMessage) ProtoMessage() {}

func (x *NetScanInMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetScanInMessage.ProtoReflect.Descriptor instead.
func (*NetScanInMessage) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{10}
}

func (x *NetScanInMessage) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *NetScanInMessage) GetIpRange() string {
	if x != nil {
		return x.IpRange
	}
	return ""
}

func (x *NetScanInMessage) GetFilterIPList() []string {
	if x != nil {
		return x.FilterIPList
	}
	return nil
}

func (x *NetScanInMessage) GetNetID() uint32 {
	if x != nil {
		return x.NetID
	}
	return 0
}

type NetScanOutMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	End           bool                   `protobuf:"varint,1,opt,name=end,proto3" json:"end,omitempty"`            // 是否结束
	Progress      float32                `protobuf:"fixed32,2,opt,name=progress,proto3" json:"progress,omitempty"` // 扫描进度
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`               // mac
	Mac           string                 `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`             // ip
	Manuf         string                 `protobuf:"bytes,5,opt,name=manuf,proto3" json:"manuf,omitempty"`         // mac对应的厂商
	NetID         uint32                 `protobuf:"varint,6,opt,name=netID,proto3" json:"netID,omitempty"`        // 网络id
	ErrMsg        string                 `protobuf:"bytes,7,opt,name=errMsg,proto3" json:"errMsg,omitempty"`       // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetScanOutMessage) Reset() {
	*x = NetScanOutMessage{}
	mi := &file_internal_rpc_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetScanOutMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetScanOutMessage) ProtoMessage() {}

func (x *NetScanOutMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetScanOutMessage.ProtoReflect.Descriptor instead.
func (*NetScanOutMessage) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{11}
}

func (x *NetScanOutMessage) GetEnd() bool {
	if x != nil {
		return x.End
	}
	return false
}

func (x *NetScanOutMessage) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *NetScanOutMessage) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NetScanOutMessage) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *NetScanOutMessage) GetManuf() string {
	if x != nil {
		return x.Manuf
	}
	return ""
}

func (x *NetScanOutMessage) GetNetID() uint32 {
	if x != nil {
		return x.NetID
	}
	return 0
}

func (x *NetScanOutMessage) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type NodeRemoveInMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRemoveInMessage) Reset() {
	*x = NodeRemoveInMessage{}
	mi := &file_internal_rpc_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRemoveInMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRemoveInMessage) ProtoMessage() {}

func (x *NodeRemoveInMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRemoveInMessage.ProtoReflect.Descriptor instead.
func (*NodeRemoveInMessage) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{12}
}

type NodeRemoveOutMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRemoveOutMessage) Reset() {
	*x = NodeRemoveOutMessage{}
	mi := &file_internal_rpc_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRemoveOutMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRemoveOutMessage) ProtoMessage() {}

func (x *NodeRemoveOutMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRemoveOutMessage.ProtoReflect.Descriptor instead.
func (*NodeRemoveOutMessage) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{13}
}

var File_internal_rpc_node_proto protoreflect.FileDescriptor

const file_internal_rpc_node_proto_rawDesc = "" +
	"\n" +
	"\x17internal/rpc/node.proto\x12\bnode_rpc\"4\n" +
	"\fBaseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xbc\x02\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x19\n" +
	"\bnode_uid\x18\x03 \x01(\tR\anodeUid\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x05 \x01(\tR\x06commit\x12;\n" +
	"\n" +
	"systemInfo\x18\x06 \x01(\v2\x1b.node_rpc.SystemInfoMessageR\n" +
	"systemInfo\x12=\n" +
	"\fresourceInfo\x18\a \x01(\v2\x19.node_rpc.ResourceMessageR\fresourceInfo\x12>\n" +
	"\vnetworkList\x18\b \x03(\v2\x1c.node_rpc.NetworkInfoMessageR\vnetworkList\"o\n" +
	"\x13NodeResourceRequest\x12\x19\n" +
	"\bnode_uid\x18\x01 \x01(\tR\anodeUid\x12=\n" +
	"\fresourceInfo\x18\x02 \x01(\v2\x19.node_rpc.ResourceMessageR\fresourceInfo\"\xc1\x01\n" +
	"\x11SystemInfoMessage\x12\x1a\n" +
	"\bhostName\x18\x01 \x01(\tR\bhostName\x120\n" +
	"\x13distributionVersion\x18\x02 \x01(\tR\x13distributionVersion\x12 \n" +
	"\vcoreVersion\x18\x03 \x01(\tR\vcoreVersion\x12\x1e\n" +
	"\n" +
	"systemType\x18\x04 \x01(\tR\n" +
	"systemType\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\tR\tstartTime\"\x9b\x02\n" +
	"\x0fResourceMessage\x12\x1a\n" +
	"\bcpuCount\x18\x01 \x01(\x03R\bcpuCount\x12\x1e\n" +
	"\n" +
	"cpuUseRate\x18\x02 \x01(\x02R\n" +
	"cpuUseRate\x12\x1a\n" +
	"\bmemTotal\x18\x03 \x01(\x03R\bmemTotal\x12\x1e\n" +
	"\n" +
	"memUseRate\x18\x04 \x01(\x02R\n" +
	"memUseRate\x12\x1c\n" +
	"\tdiskTotal\x18\x05 \x01(\x03R\tdiskTotal\x12 \n" +
	"\vdiskUseRate\x18\x06 \x01(\x02R\vdiskUseRate\x12\x1a\n" +
	"\bnodePath\x18\a \x01(\tR\bnodePath\x124\n" +
	"\x15nodeResourceOccupancy\x18\b \x01(\x03R\x15nodeResourceOccupancy\"d\n" +
	"\x12NetworkInfoMessage\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x10\n" +
	"\x03net\x18\x03 \x01(\tR\x03net\x12\x12\n" +
	"\x04mask\x18\x04 \x01(\x05R\x04mask\"\xc1\x02\n" +
	"\n" +
	"CmdRequest\x12+\n" +
	"\acmdType\x18\x01 \x01(\x0e2\x11.node_rpc.CmdTypeR\acmdType\x12\x16\n" +
	"\x06taskID\x18\x02 \x01(\tR\x06taskID\x12U\n" +
	"\x15NetworkFlushInMessage\x18\x03 \x01(\v2\x1f.node_rpc.NetworkFlushInMessageR\x15NetworkFlushInMessage\x12F\n" +
	"\x10NetScanInMessage\x18\x04 \x01(\v2\x1a.node_rpc.NetScanInMessageR\x10NetScanInMessage\x12O\n" +
	"\x13NodeRemoveInMessage\x18\x05 \x01(\v2\x1d.node_rpc.NodeRemoveInMessageR\x13NodeRemoveInMessage\"\x93\x03\n" +
	"\vCmdResponse\x12+\n" +
	"\acmdType\x18\x01 \x01(\x0e2\x11.node_rpc.CmdTypeR\acmdType\x12\x16\n" +
	"\x06taskID\x18\x02 \x01(\tR\x06taskID\x12\x16\n" +
	"\x06nodeID\x18\x03 \x01(\tR\x06nodeID\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\x12\x1a\n" +
	"\berrorMsg\x18\x05 \x01(\tR\berrorMsg\x12X\n" +
	"\x16NetworkFlushOutMessage\x18\x06 \x01(\v2 .node_rpc.NetworkFlushOutMessageR\x16NetworkFlushOutMessage\x12I\n" +
	"\x11NetScanOutMessage\x18\a \x01(\v2\x1b.node_rpc.NetScanOutMessageR\x11NetScanOutMessage\x12R\n" +
	"\x14NodeRemoveOutMessage\x18\b \x01(\v2\x1e.node_rpc.NodeRemoveOutMessageR\x14NodeRemoveOutMessage\"E\n" +
	"\x15NetworkFlushInMessage\x12,\n" +
	"\x11filterNetworkName\x18\x01 \x03(\tR\x11filterNetworkName\"X\n" +
	"\x16NetworkFlushOutMessage\x12>\n" +
	"\vnetworkList\x18\x01 \x03(\v2\x1c.node_rpc.NetworkInfoMessageR\vnetworkList\"\x80\x01\n" +
	"\x10NetScanInMessage\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x18\n" +
	"\aipRange\x18\x02 \x01(\tR\aipRange\x12\"\n" +
	"\ffilterIPList\x18\x03 \x03(\tR\ffilterIPList\x12\x14\n" +
	"\x05netID\x18\x04 \x01(\rR\x05netID\"\xa7\x01\n" +
	"\x11NetScanOutMessage\x12\x10\n" +
	"\x03end\x18\x01 \x01(\bR\x03end\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x02R\bprogress\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x04 \x01(\tR\x03mac\x12\x14\n" +
	"\x05manuf\x18\x05 \x01(\tR\x05manuf\x12\x14\n" +
	"\x05netID\x18\x06 \x01(\rR\x05netID\x12\x16\n" +
	"\x06errMsg\x18\a \x01(\tR\x06errMsg\"\x15\n" +
	"\x13NodeRemoveInMessage\"\x16\n" +
	"\x14NodeRemoveOutMessage*^\n" +
	"\aCmdType\x12\x17\n" +
	"\x13cmdNetworkFlushType\x10\x00\x12\x12\n" +
	"\x0ecmdNetScanType\x10\x01\x12\x15\n" +
	"\x11cmdNodeRemoveType\x10\x02\x12\x0f\n" +
	"\vcmdPingType\x10\x032\xd5\x01\n" +
	"\vNodeService\x12?\n" +
	"\bRegister\x12\x19.node_rpc.RegisterRequest\x1a\x16.node_rpc.BaseResponse\"\x00\x12G\n" +
	"\fNodeResource\x12\x1d.node_rpc.NodeResourceRequest\x1a\x16.node_rpc.BaseResponse\"\x00\x12<\n" +
	"\aCommand\x12\x15.node_rpc.CmdResponse\x1a\x14.node_rpc.CmdRequest\"\x00(\x010\x01B\vZ\t/node_rpcb\x06proto3"

var (
	file_internal_rpc_node_proto_rawDescOnce sync.Once
	file_internal_rpc_node_proto_rawDescData []byte
)

func file_internal_rpc_node_proto_rawDescGZIP() []byte {
	file_internal_rpc_node_proto_rawDescOnce.Do(func() {
		file_internal_rpc_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_node_proto_rawDesc), len(file_internal_rpc_node_proto_rawDesc)))
	})
	return file_internal_rpc_node_proto_rawDescData
}

var file_internal_rpc_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_rpc_node_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_rpc_node_proto_goTypes = []any{
	(CmdType)(0),                   // 0: node_rpc.CmdType
	(*BaseResponse)(nil),           // 1: node_rpc.BaseResponse
	(*RegisterRequest)(nil),        // 2: node_rpc.RegisterRequest
	(*NodeResourceRequest)(nil),    // 3: node_rpc.NodeResourceRequest
	(*SystemInfoMessage)(nil),      // 4: node_rpc.SystemInfoMessage
	(*ResourceMessage)(nil),        // 5: node_rpc.ResourceMessage
	(*NetworkInfoMessage)(nil),     // 6: node_rpc.NetworkInfoMessage
	(*CmdRequest)(nil),             // 7: node_rpc.CmdRequest
	(*CmdResponse)(nil),            // 8: node_rpc.CmdResponse
	(*NetworkFlushInMessage)(nil),  // 9: node_rpc.NetworkFlushInMessage
	(*NetworkFlushOutMessage)(nil), // 10: node_rpc.NetworkFlushOutMessage
	(*NetScanInMessage)(nil),       // 11: node_rpc.NetScanInMessage
	(*NetScanOutMessage)(nil),      // 12: node_rpc.NetScanOutMessage
	(*NodeRemoveInMessage)(nil),    // 13: node_rpc.NodeRemoveInMessage
	(*NodeRemoveOutMessage)(nil),   // 14: node_rpc.NodeRemoveOutMessage
}
var file_internal_rpc_node_proto_depIdxs = []int32{
	4,  // 0: node_rpc.RegisterRequest.systemInfo:type_name -> node_rpc.SystemInfoMessage
	5,  // 1: node_rpc.RegisterRequest.resourceInfo:type_name -> node_rpc.ResourceMessage
	6,  // 2: node_rpc.RegisterRequest.networkList:type_name -> node_rpc.NetworkInfoMessage
	5,  // 3: node_rpc.NodeResourceRequest.resourceInfo:type_name -> node_rpc.ResourceMessage
	0,  // 4: node_rpc.CmdRequest.cmdType:type_name -> node_rpc.CmdType
	9,  // 5: node_rpc.CmdRequest.NetworkFlushInMessage:type_name -> node_rpc.NetworkFlushInMessage
	11, // 6: node_rpc.CmdRequest.NetScanInMessage:type_name -> node_rpc.NetScanInMessage
	13, // 7: node_rpc.CmdRequest.NodeRemoveInMessage:type_name -> node_rpc.NodeRemoveInMessage
	0,  // 8: node_rpc.CmdResponse.cmdType:type_name -> node_rpc.CmdType
	10, // 9: node_rpc.CmdResponse.NetworkFlushOutMessage:type_name -> node_rpc.NetworkFlushOutMessage
	12, // 10: node_rpc.CmdResponse.NetScanOutMessage:type_name -> node_rpc.NetScanOutMessage
	14, // 11: node_rpc.CmdResponse.NodeRemoveOutMessage:type_name -> node_rpc.NodeRemoveOutMessage
	6,  // 12: node_rpc.NetworkFlushOutMessage.networkList:type_name -> node_rpc.NetworkInfoMessage
	2,  // 13: node_rpc.NodeService.Register:input_type -> node_rpc.RegisterRequest
	3,  // 14: node_rpc.NodeService.NodeResource:input_type -> node_rpc.NodeResourceRequest
	8,  // 15: node_rpc.NodeService.Command:input_type -> node_rpc.CmdResponse
	1,  // 16: node_rpc.NodeService.Register:output_type -> node_rpc.BaseResponse
	1,  // 17: node_rpc.NodeService.NodeResource:output_type -> node_rpc.BaseResponse
	7,  // 18: node_rpc.NodeService.Command:output_type -> node_rpc.CmdRequest
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_rpc_node_proto_init() }
func file_internal_rpc_node_proto_init() {
	if File_internal_rpc_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_node_proto_rawDesc), len(file_internal_rpc_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_node_proto_goTypes,
		DependencyIndexes: file_internal_rpc_node_proto_depIdxs,
		EnumInfos:         file_internal_rpc_node_proto_enumTypes,
		MessageInfos:      file_internal_rpc_node_proto_msgTypes,
	}.Build()
	File_internal_rpc_node_proto = out.File
	file_internal_rpc_node_proto_goTypes = nil
	file_internal_rpc_node_proto_depIdxs = nil
}
