db:
  db_name: "honey_db"
  host: "111.111.111.133"
  port: 3306
  user: "root"
  password: "123456"
  maxIdleConns: 2
  maxOpenConns: 100
  connMaxLifeTime: 10000
logger:
  format: json
  appName: honey_server
  level: info
redis:
  addr: "111.111.111.133:6379"
  password:
  db: 1
system:
  webAddr: "0.0.0.0:8080"  # web的运行地址
jwt:
  expires: 8640000
  issuer: chenxia
  secret: chenx@qq.com
whiteList:
  - /image_server/mirror_cloud/see
  - /image_server/mirror_cloud
vsNet:
  name: "honey-hy"
  prefix: hy-
  net: "10.2.0.0/24"