// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: internal/rpc/node.proto

package node_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_internal_rpc_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// HelloRequest 请求内容
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	NodeUid       string                 `protobuf:"bytes,3,opt,name=node_uid,json=nodeUid,proto3" json:"node_uid,omitempty"` // 消息号
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,5,opt,name=commit,proto3" json:"commit,omitempty"`
	SystemInfo    *SystemInfoMessage     `protobuf:"bytes,6,opt,name=systemInfo,proto3" json:"systemInfo,omitempty"`
	ResourceInfo  *ResourceMessage       `protobuf:"bytes,7,opt,name=resourceInfo,proto3" json:"resourceInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_rpc_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *RegisterRequest) GetNodeUid() string {
	if x != nil {
		return x.NodeUid
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *RegisterRequest) GetSystemInfo() *SystemInfoMessage {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

func (x *RegisterRequest) GetResourceInfo() *ResourceMessage {
	if x != nil {
		return x.ResourceInfo
	}
	return nil
}

type NodeResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeUid       string                 `protobuf:"bytes,1,opt,name=node_uid,json=nodeUid,proto3" json:"node_uid,omitempty"` // 消息号
	ResourceInfo  *ResourceMessage       `protobuf:"bytes,2,opt,name=resourceInfo,proto3" json:"resourceInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResourceRequest) Reset() {
	*x = NodeResourceRequest{}
	mi := &file_internal_rpc_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResourceRequest) ProtoMessage() {}

func (x *NodeResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResourceRequest.ProtoReflect.Descriptor instead.
func (*NodeResourceRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{2}
}

func (x *NodeResourceRequest) GetNodeUid() string {
	if x != nil {
		return x.NodeUid
	}
	return ""
}

func (x *NodeResourceRequest) GetResourceInfo() *ResourceMessage {
	if x != nil {
		return x.ResourceInfo
	}
	return nil
}

type SystemInfoMessage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HostName            string                 `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	DistributionVersion string                 `protobuf:"bytes,2,opt,name=distributionVersion,proto3" json:"distributionVersion,omitempty"`
	CoreVersion         string                 `protobuf:"bytes,3,opt,name=coreVersion,proto3" json:"coreVersion,omitempty"`
	SystemType          string                 `protobuf:"bytes,4,opt,name=systemType,proto3" json:"systemType,omitempty"`
	StartTime           string                 `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SystemInfoMessage) Reset() {
	*x = SystemInfoMessage{}
	mi := &file_internal_rpc_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoMessage) ProtoMessage() {}

func (x *SystemInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoMessage.ProtoReflect.Descriptor instead.
func (*SystemInfoMessage) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{3}
}

func (x *SystemInfoMessage) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *SystemInfoMessage) GetDistributionVersion() string {
	if x != nil {
		return x.DistributionVersion
	}
	return ""
}

func (x *SystemInfoMessage) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *SystemInfoMessage) GetSystemType() string {
	if x != nil {
		return x.SystemType
	}
	return ""
}

func (x *SystemInfoMessage) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

type ResourceMessage struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CpuCount              int64                  `protobuf:"varint,1,opt,name=cpuCount,proto3" json:"cpuCount,omitempty"`
	CpuUseRate            float32                `protobuf:"fixed32,2,opt,name=cpuUseRate,proto3" json:"cpuUseRate,omitempty"`
	MemTotal              int64                  `protobuf:"varint,3,opt,name=memTotal,proto3" json:"memTotal,omitempty"`
	MemUseRate            float32                `protobuf:"fixed32,4,opt,name=memUseRate,proto3" json:"memUseRate,omitempty"`
	DiskTotal             int64                  `protobuf:"varint,5,opt,name=diskTotal,proto3" json:"diskTotal,omitempty"`
	DiskUseRate           float32                `protobuf:"fixed32,6,opt,name=diskUseRate,proto3" json:"diskUseRate,omitempty"`
	NodePath              string                 `protobuf:"bytes,7,opt,name=nodePath,proto3" json:"nodePath,omitempty"`
	NodeResourceOccupancy int64                  `protobuf:"varint,8,opt,name=nodeResourceOccupancy,proto3" json:"nodeResourceOccupancy,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ResourceMessage) Reset() {
	*x = ResourceMessage{}
	mi := &file_internal_rpc_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMessage) ProtoMessage() {}

func (x *ResourceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMessage.ProtoReflect.Descriptor instead.
func (*ResourceMessage) Descriptor() ([]byte, []int) {
	return file_internal_rpc_node_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceMessage) GetCpuCount() int64 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *ResourceMessage) GetCpuUseRate() float32 {
	if x != nil {
		return x.CpuUseRate
	}
	return 0
}

func (x *ResourceMessage) GetMemTotal() int64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *ResourceMessage) GetMemUseRate() float32 {
	if x != nil {
		return x.MemUseRate
	}
	return 0
}

func (x *ResourceMessage) GetDiskTotal() int64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *ResourceMessage) GetDiskUseRate() float32 {
	if x != nil {
		return x.DiskUseRate
	}
	return 0
}

func (x *ResourceMessage) GetNodePath() string {
	if x != nil {
		return x.NodePath
	}
	return ""
}

func (x *ResourceMessage) GetNodeResourceOccupancy() int64 {
	if x != nil {
		return x.NodeResourceOccupancy
	}
	return 0
}

var File_internal_rpc_node_proto protoreflect.FileDescriptor

const file_internal_rpc_node_proto_rawDesc = "" +
	"\n" +
	"\x17internal/rpc/node.proto\x12\bnode_rpc\"4\n" +
	"\fBaseResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xfc\x01\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x19\n" +
	"\bnode_uid\x18\x03 \x01(\tR\anodeUid\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x05 \x01(\tR\x06commit\x12;\n" +
	"\n" +
	"systemInfo\x18\x06 \x01(\v2\x1b.node_rpc.systemInfoMessageR\n" +
	"systemInfo\x12=\n" +
	"\fresourceInfo\x18\a \x01(\v2\x19.node_rpc.resourceMessageR\fresourceInfo\"o\n" +
	"\x13NodeResourceRequest\x12\x19\n" +
	"\bnode_uid\x18\x01 \x01(\tR\anodeUid\x12=\n" +
	"\fresourceInfo\x18\x02 \x01(\v2\x19.node_rpc.resourceMessageR\fresourceInfo\"\xc1\x01\n" +
	"\x11systemInfoMessage\x12\x1a\n" +
	"\bhostName\x18\x01 \x01(\tR\bhostName\x120\n" +
	"\x13distributionVersion\x18\x02 \x01(\tR\x13distributionVersion\x12 \n" +
	"\vcoreVersion\x18\x03 \x01(\tR\vcoreVersion\x12\x1e\n" +
	"\n" +
	"systemType\x18\x04 \x01(\tR\n" +
	"systemType\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\tR\tstartTime\"\x9b\x02\n" +
	"\x0fresourceMessage\x12\x1a\n" +
	"\bcpuCount\x18\x01 \x01(\x03R\bcpuCount\x12\x1e\n" +
	"\n" +
	"cpuUseRate\x18\x02 \x01(\x02R\n" +
	"cpuUseRate\x12\x1a\n" +
	"\bmemTotal\x18\x03 \x01(\x03R\bmemTotal\x12\x1e\n" +
	"\n" +
	"memUseRate\x18\x04 \x01(\x02R\n" +
	"memUseRate\x12\x1c\n" +
	"\tdiskTotal\x18\x05 \x01(\x03R\tdiskTotal\x12 \n" +
	"\vdiskUseRate\x18\x06 \x01(\x02R\vdiskUseRate\x12\x1a\n" +
	"\bnodePath\x18\a \x01(\tR\bnodePath\x124\n" +
	"\x15nodeResourceOccupancy\x18\b \x01(\x03R\x15nodeResourceOccupancy2\x97\x01\n" +
	"\vNodeService\x12?\n" +
	"\bRegister\x12\x19.node_rpc.RegisterRequest\x1a\x16.node_rpc.BaseResponse\"\x00\x12G\n" +
	"\fNodeResource\x12\x1d.node_rpc.NodeResourceRequest\x1a\x16.node_rpc.BaseResponse\"\x00B\vZ\t/node_rpcb\x06proto3"

var (
	file_internal_rpc_node_proto_rawDescOnce sync.Once
	file_internal_rpc_node_proto_rawDescData []byte
)

func file_internal_rpc_node_proto_rawDescGZIP() []byte {
	file_internal_rpc_node_proto_rawDescOnce.Do(func() {
		file_internal_rpc_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_node_proto_rawDesc), len(file_internal_rpc_node_proto_rawDesc)))
	})
	return file_internal_rpc_node_proto_rawDescData
}

var file_internal_rpc_node_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_rpc_node_proto_goTypes = []any{
	(*BaseResponse)(nil),        // 0: node_rpc.BaseResponse
	(*RegisterRequest)(nil),     // 1: node_rpc.RegisterRequest
	(*NodeResourceRequest)(nil), // 2: node_rpc.NodeResourceRequest
	(*SystemInfoMessage)(nil),   // 3: node_rpc.systemInfoMessage
	(*ResourceMessage)(nil),     // 4: node_rpc.resourceMessage
}
var file_internal_rpc_node_proto_depIdxs = []int32{
	3, // 0: node_rpc.RegisterRequest.systemInfo:type_name -> node_rpc.systemInfoMessage
	4, // 1: node_rpc.RegisterRequest.resourceInfo:type_name -> node_rpc.resourceMessage
	4, // 2: node_rpc.NodeResourceRequest.resourceInfo:type_name -> node_rpc.resourceMessage
	1, // 3: node_rpc.NodeService.Register:input_type -> node_rpc.RegisterRequest
	2, // 4: node_rpc.NodeService.NodeResource:input_type -> node_rpc.NodeResourceRequest
	0, // 5: node_rpc.NodeService.Register:output_type -> node_rpc.BaseResponse
	0, // 6: node_rpc.NodeService.NodeResource:output_type -> node_rpc.BaseResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_rpc_node_proto_init() }
func file_internal_rpc_node_proto_init() {
	if File_internal_rpc_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_node_proto_rawDesc), len(file_internal_rpc_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_node_proto_goTypes,
		DependencyIndexes: file_internal_rpc_node_proto_depIdxs,
		MessageInfos:      file_internal_rpc_node_proto_msgTypes,
	}.Build()
	File_internal_rpc_node_proto = out.File
	file_internal_rpc_node_proto_goTypes = nil
	file_internal_rpc_node_proto_depIdxs = nil
}
