db:
  db_name: "honey_db"
  host: "111.111.111.133"
  port: 3306
  user: "root"
  password: "123456"
  maxIdleConns: 2
  maxOpenConns: 100
  connMaxLifeTime: 10000
logger:
  format: json
  appName: alert_server
  level: info
redis:
  addr: "111.111.111.133:6379"
  password:
  db: 1
system:
  webAddr: "0.0.0.0:8078"    # web的运行地址
jwt:
  expires: 8640000
  issuer: chenxia
  secret: chenx@qq.com
whiteList:
  - /honey_server/login
  - /honey_server/captcha
  - /honey_server/site
mq:
  user: admin
  password: password
  host: 111.111.111.133
  port: 5671
  createIpExchangeName: createIpExchange
  deleteIpExchangeName: deleteIpExchange
  bindPortExchangeName: bindPortExchange
  ssl: true
  clientCertificate: mq_cert/client_certificate.pem #客户端证书
  clientKey: mq_cert/client_key.pem           #客户端私钥
  caCertificate: mq_cert/ca_certificate.pem        #ca证书

es:
  addr: http://111.111.111.133:9200
  userName:
  password: