syntax = "proto3";    // 指定proto版本
package node_rpc;     // 指定默认包名

// 指定golang包名
option go_package = "/node_rpc";

//定义rpc服务
service NodeService {
  // 定义函数
  rpc Register (RegisterRequest) returns (BaseResponse) {}
}

message BaseResponse {
  int32 code = 1;
  string msg = 2;
}

// HelloRequest 请求内容
message RegisterRequest {
  string ip = 1;
  string mac = 2;
  string node_uid = 3;  // 消息号
  string version = 4;
  string commit = 5;
}

// proto --go_out=. --go-grpc_out=. *.proto

// HelloResponse 响应内容
//message RegisterResponse {
//  string name = 1;
//  string message = 2;
//}